get: 
  tags: 
    -  Product
  summary: Get a list of products by manufacturer
  description: Get a list of products by manufacturer.
  operationId: listProductsByManufacturer
  responses: 
    '200': 
      description: Success
      content: 
        application/json: 
          schema: 
            $ref: ../../components/schemas/v1/product_list.yaml  
    '404': 
      description: Not Found
      content: 
        application/json: 
          schema: 
            $ref: ../../components/schemas/Problem.yaml     