get: 
  tags: 
    -  Product 
  summary: Get a list of products by manufacturer
  description:  |
    Get a list of products by manufacturer
  operationId: getProductByManufacturer
  parameters: 
    - name: product_manufacturer
      in: path
      description: The manufacturer of the list of products to retrieve
      required: true
      schema: 
        type: string
        format: uuid
  responses:
    '200':
      description: successful operation
      content:
        application/json:
          schema:
            $ref: ../../components/schemas/v1/product.yaml
    '400':
      description: Bad Request 
    '404':
      description: Not Found